# Generated by Django 5.1.3 on 2025-01-11 23:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
            ],
        ),
    ]
