# Generated by Django 5.1.3 on 2025-01-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brandgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandgallery',
            name='category',
        ),
    ]
