# Generated by Django 5.1.3 on 2025-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brandgallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='hero_image',
            field=models.ImageField(blank=True, default='brand_images/default.png', null=True, upload_to='brand_images/'),
        ),
    ]
