# Generated by Django 5.1.3 on 2025-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_alter_brand_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='brand_images/default.png', null=True, upload_to='brand_logos/'),
        ),
    ]
