# Generated by Django 5.1.3 on 2025-01-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_replied_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replied_to',
        ),
    ]
