# Generated by Django 5.1.3 on 2025-02-01 14:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_subservice_subserviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
