# Generated by Django 5.1.3 on 2025-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_subservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, default='service_images/default.png', null=True, upload_to='service_images/'),
        ),
    ]
