# Generated by Django 5.1.3 on 2025-02-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_service_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviceimage',
            name='image',
            field=models.ImageField(default='subservice_images/default_image.jpg', upload_to='subservice_images/'),
        ),
    ]
