# Generated by Django 5.1.3 on 2025-02-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_pdf_file_brochure_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
