"""
Django settings for skyhigh project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xar)ng*rf%=baor!@v$xh9p_co&8gjl%=+2%0aa75_mdst)c+w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['178.128.101.148', 'skyhigh-inter.com', 'www.skyhigh-inter.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main',
    'blog',
    'users',
    'brand',

    'crispy_forms',
    'crispy_bootstrap5',
    'ckeditor',
    'ckeditor_uploader',  # For CKEditor 5


    'whitenoise.runserver_nostatic', #Make sure to add this 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skyhigh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.tags_processor', 
            ],
        },
    },
]

WSGI_APPLICATION = 'skyhigh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Ensure the path matches your project
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'skyhigh10280@gmail.com'
EMAIL_HOST_PASSWORD = 'tads lwpp vjqz esig'

# Default From Email
DEFAULT_FROM_EMAIL = 'skyhigh10280@gmail.com'

# Admins to receive notifications
ADMINS = [('Sonuadmin', 'skyhigh10280@gmail.com')]



CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 'auto',
        'extraPlugins': ','.join(['image2']),  # Enables image plugin
    },
}

CKEDITOR_UPLOAD_PATH = "uploads/"  # Directory for uploaded files
CKEDITOR_IMAGE_BACKEND = "pillow"  # Use Pillow for image processing

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

RECAPTCHA_PUBLIC_KEY = "6LeTg9EqAAAAABaRsXk0QYdz_JrQElslFCqsltae"
RECAPTCHA_PRIVATE_KEY = "6LeTg9EqAAAAAMqkCikTMh4waEVZ6fZ260LcBM4i"



import os

# reCAPTCHA for local development
if os.getenv("DJANGO_ENV") == "development":
    RECAPTCHA_SITE_KEY = "6LdsktEqAAAAAHkEmKvlCdpW6pLl0M4FIQC9sMA0"
    RECAPTCHA_SECRET_KEY = "6LdsktEqAAAAALecFhdD90fphpVYiinxmDp1r6ci"
else:
    # reCAPTCHA for production
    RECAPTCHA_SITE_KEY = "6LdsktEqAAAAAHkEmKvlCdpW6pLl0M4FIQC9sMA0"
    RECAPTCHA_SECRET_KEY = "6LdsktEqAAAAALecFhdD90fphpVYiinxmDp1r6ci"
